package ru.kest.trainswidget

/**
 * Project Constants
 *
 * Created by Konstantin on 26.05.2017.
 */

// Time limits
val HOME_RED_STATUS = 15
val HOME_YELLOW_STATUS = 25
val HOME_GREEN_STATUS = 40
//    int HOME_WHITE_STATUS = 40;
val HOME_FIRST_CALL = 12
val HOME_LAST_CALL = 6

val WORK_RED_STATUS = 20
val WORK_YELLOW_STATUS = 25
val WORK_GREEN_STATUS = 35
//    int WORK_WHITE_STATUS = 50;
val WORK_FIRST_CALL = 25
val WORK_LAST_CALL = 20

// static preferences
val ELEMENT_COUNT = 4

// General
val LOG_TAG = "trainsWidgetLogs"
val PACKAGE_NAME = "ru.kest.trainswidget"

// Actions
val UPDATE_ALL_WIDGETS = "UPDATE_ALL_WIDGETS"
val UPDATE_LOCATION = "UPDATE_LOCATION"
val TRAIN_SCHEDULE_REQUEST = "TRAIN_SCHEDULE_REQUEST"
val CREATE_NOTIFICATION = "CREATE_NOTIFICATION"
val UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION"
val DELETED_NOTIFICATION = "DELETED_NOTIFICATION"

// Extras
val RECORD_HASH = "RECORD_HASH"
val DETAILS = "DETAILS"

// Notification
val NOTIFICATION_ID = 1

// Time limit labels
val RED_STATUS = "RED_STATUS"
val YELLOW_STATUS = "YELLOW_STATUS"
val GREEN_STATUS = "GREEN_STATUS"
//    String WHITE_STATUS = "WHITE_STATUS";
val FIRST_CALL = "FIRST_CALL"
val LAST_CALL = "LAST_CALL"


